### ISSUE TITLE
console errors on latest deployment

### ISSUE THREAD

**Issue by jasonduley** [nasa/code-nasa-gov#16]
angular.js:13708 Error: [ngRepeat:dupes] http://errors.angularjs.org/1.5.7/ngRepeat/dupes?p0=license%20in%20project.License%20%7C%20orderBy%3Alicense&p1=string%3A%20&p2=%20
    at Error (native)
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:6:412
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:301:39
    at http://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:141:337
    at m.$digest (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:142:442)
    at m.$apply (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:145:401)
    at l (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:97:250)
    at K (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:101:373)
    at XMLHttpRequest.y.onload (http://ajax.googleapis.com/ajax/libs/angularjs/1.5.7/angular.min.js:102:397)

**Comment by addyosmani** [comment]
I've tried reproducing this locally with the latest checkout from master but can't seem to just yet:

![](https://i.imgur.com/dq40yo6.jpg)

Definitely is happening on prod. Will keep looking into cause.
